#!/bin/bash
set -eu -o pipefail

OUTPUT_FILE=/opt/guardian/bin/run-init-guardian

VAULT_DNS=$1
VAULT_PORT=$2

VAULT_URL="https://$VAULT_DNS:$VAULT_PORT"

# Write the run-init-guardian script
cat << EOF_OUTER > $OUTPUT_FILE
#!/bin/bash
set -eu -o pipefail

SUPERVISOR_CONFIG="/etc/supervisor/conf.d/init-guardian-supervisor.conf"

# Write the init-guardian supervisor config
cat << EOF > \$SUPERVISOR_CONFIG
[program:init-guardian]
command=/opt/guardian/bin/init-guardian.sh
stdout_logfile=/opt/guardian/log/init-guardian-stdout.log
stderr_logfile=/opt/guardian/log/init-guardian-error.log
numprocs=1
autostart=true
autorestart=unexpected
stopsignal=INT
user=ubuntu
environment=VAULT_ADDR=$VAULT_URL
EOF

# Read and run the supervisor config
sudo supervisorctl reread
sudo supervisorctl update
EOF_OUTER

# Give permission to run the script
sudo chown ubuntu $OUTPUT_FILE
sudo chmod 744 $OUTPUT_FILE
